In [1]:
from main import main

In [2]:
X, y = main()

Full dataset shape: (4271, 353)
Dataset shape after drop columns and nan target: (4271, 282)

In [14]:
X.describe()

,P2_l_1,P2_l_2,P2_l_3,P2_l_4,P2_l_5,P2_l_6,P2_l_7,P2_o_1,P2_o_2,P2_o_3,...,P8_d_2,P8_d_3,P8_d_4,P8_d_5,P8_d_6,P8_d_7,P8_d_8,P8_d_9,P8_d_10,P8_d_11
count,960.000000,960.000000,960.000000,960.000000,960.000000,960.000000,960.000000,3694.000000,3694.000000,3694.000000,...,629.000000,629.000000,629.000000,629.000000,629.000000,629.000000,629.000000,629.000000,629.000000,629.000000
mean,0.436458,0.389583,0.066667,0.321875,0.184375,0.142708,0.383333,0.750677,0.192745,0.173795,...,0.478537,0.248013,0.324324,0.095390,0.057234,0.065183,0.006359,0.031797,0.019078,0.015898
std,0.496205,0.487910,0.249574,0.467439,0.387992,0.349957,0.486452,0.432680,0.394508,0.378985,...,0.499937,0.432203,0.468494,0.293986,0.232473,0.247045,0.079555,0.175598,0.136908,0.125182
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [3]:
X.head()

,P1_l,P1_m,P2_i,P2_j,P2_l_1,P2_l_2,P2_l_3,P2_l_4,P2_l_5,P2_l_6,...,P8_d_2,P8_d_3,P8_d_4,P8_d_5,P8_d_6,P8_d_7,P8_d_8,P8_d_9,P8_d_10,P8_d_11
0,PÃ³s-graduaÃ§Ã£o,ComputaÃ§Ã£o / Engenharia de Software / Sistemas...,de 1 a 2 anos,de 7 a 10 anos,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,GraduaÃ§Ã£o/Bacharelado,Outras Engenharias,de 3 a 4 anos,Menos de 1 ano,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PÃ³s-graduaÃ§Ã£o,ComputaÃ§Ã£o / Engenharia de Software / Sistemas...,de 3 a 4 anos,Mais de 10 anos,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Doutorado ou Phd,EstatÃ­stica/ MatemÃ¡tica / MatemÃ¡tica Computaci...,de 4 a 6 anos,NÃ£o tive experiÃªncia na Ã¡rea de TI/Engenharia ...,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,PÃ³s-graduaÃ§Ã£o,ComputaÃ§Ã£o / Engenharia de Software / Sistemas...,NÃ£o tenho experiÃªncia na Ã¡rea de dados,Mais de 10 anos,1.0,0.0,0.0,0.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
import lightgbm as lgb
from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define LightGBM model for multiclass classification
lgbm_classifier = lgb.LGBMClassifier(objective='multiclass', num_classes=len(y.unique()))

# Train the model
lgbm_classifier.fit(X_train, y_train)

# Evaluate the model
accuracy = lgbm_classifier.score(X_test, y_test)
print("Accuracy:", accuracy)

ValueError: pandas dtypes must be int, float or bool.
Fields with bad pandas dtypes: P1_l: object, P1_m: object, P2_i: object, P2_j: object, P2_p: object, P4_i: object, P6_c: object, P6_e: object

In [13]:
for column in X.columns:
    if isinstance(X[column], bool):
        print(column)
    else:
        pass

In [7]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3694 entries, 0 to 4270
Columns: 282 entries, P1_l to P8_d_11
dtypes: float64(274), object(8)
memory usage: 8.0+ MB